# Generated by Django 3.0.6 on 2020-05-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200506_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author_description',
            name='description_de',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='author_description',
            name='description_en',
            field=models.TextField(max_length=500),
        ),
    ]
