# Generated by Django 3.0.6 on 2020-05-06 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200506_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skill_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_de', models.TextField(max_length=300)),
                ('description_en', models.TextField(max_length=300)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Skill')),
            ],
        ),
    ]
