# Generated by Django 3.0.6 on 2020-05-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_skill_skill_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill_description',
            name='skill',
        ),
        migrations.AddField(
            model_name='skill_description',
            name='skill',
            field=models.ManyToManyField(to='blog.Skill'),
        ),
    ]
