# Generated by Django 3.0.6 on 2020-05-07 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200507_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill_description',
            name='skill',
        ),
        migrations.AddField(
            model_name='skill_description',
            name='skill',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Skill'),
            preserve_default=False,
        ),
    ]
