# Generated by Django 3.0.6 on 2020-05-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200507_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill_description',
            name='skill',
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_description',
            field=models.ManyToManyField(related_name='skill_description', to='blog.Skill_description'),
        ),
    ]
