# Generated by Django 3.0.6 on 2020-05-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200507_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='rating',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
