# Generated by Django 3.0.6 on 2020-05-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_skill_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name_de',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name_en',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='rating',
            field=models.TextField(max_length=10),
        ),
    ]
