# Generated by Django 3.0.6 on 2020-05-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200507_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FAQ_de_text', models.TextField(max_length=300)),
                ('FAQ_en_text', models.TextField(max_length=300)),
                ('FAQ_de_answer', models.TextField(max_length=300)),
                ('FAQ_en_answer', models.TextField(max_length=300)),
            ],
        ),
    ]
