# Generated by Django 3.0.6 on 2020-05-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='FAQ_name',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
