# Generated by Django 3.0.6 on 2020-05-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_faq_faq_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal_name', models.TextField(max_length=50)),
                ('image', models.ImageField(upload_to='media/')),
                ('description_de', models.TextField(max_length=500)),
                ('description_en', models.TextField(max_length=500)),
            ],
        ),
    ]
