# Generated by Django 3.0.6 on 2020-05-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_portal'),
    ]

    operations = [
        migrations.AddField(
            model_name='portal',
            name='prolile_url',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
