# Generated by Django 3.0.6 on 2020-05-11 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_portal_prolile_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portal',
            old_name='prolile_url',
            new_name='profile_url',
        ),
    ]
